### PR TITLE
Unlocking stuck drift

### PR DESCRIPTION
**Pull request by terrateam-test-user01**

### CODE REVIEW

**Comment by terrateam-test-user01** [comment]
terrateam apply

**Comment by terrateam-test-user01** [comment]
terrateam unlock drift

**Comment by terrateam-test-user01** [comment]
terrateam apply

**Comment by terrateam-test-user01** [comment]
terrateam plan

**Comment by terrateam-test-user01** [comment]
terrateam apply

**Comment by orbitz** [comment]
terrateam unlock

**Pull request closed without merging**
