### PR TITLE
Passing pull request number into unlock unlocks it-3

### PR DESCRIPTION
**Pull request by terrateam-test-user01**

### CODE REVIEW

**Comment by terrateam-test-user01** [comment]
terrateam apply

**Comment by terrateam-test-user01** [comment]
terrateam plan

**Comment by terrateam-test-user01** [comment]
terrateam unlock 5477 5478

**Comment by terrateam-test-user01** [comment]
terrateam apply

**Comment by orbitz** [comment]
terrateam unlock

**Pull request closed without merging**
